/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-10 14:05:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.module;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import reservationManagement.*;
import memberManagement.*;

public final class economy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("memberManagement");
    _jspx_imports_packages.add("reservationManagement");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      reservationManagement.ReservationBean rbean = null;
      synchronized (session) {
        rbean = (reservationManagement.ReservationBean) _jspx_page_context.getAttribute("rbean", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (rbean == null){
          rbean = new reservationManagement.ReservationBean();
          _jspx_page_context.setAttribute("rbean", rbean, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      reservationManagement.ReservationBook rb = null;
      synchronized (session) {
        rb = (reservationManagement.ReservationBook) _jspx_page_context.getAttribute("rb", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (rb == null){
          rb = new reservationManagement.ReservationBook();
          _jspx_page_context.setAttribute("rb", rb, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("<head><link rel=\"stylesheet\" href=\"css/seat.css\" type=\"text/css\" media=\"screen\" /></head>\r\n");
      out.write("\r\n");
      out.write("<!-- economy.jsp -->\r\n");
      out.write("<body>\r\n");
      out.write("<header><!-- header 시작 -->\r\n");
      out.write("	<nav id=\"navi\"><!-- navi 시작 -->\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"index.jsp?CONTENTPAGE=content.jsp\">\r\n");
      out.write("				<img src=\"img/home.png\"></a></li>\r\n");
      out.write("			<li>&#5171;</li>\r\n");
      out.write("			<li><a href=\"index.jsp?CONTENTPAGE=reservation.jsp\">항공권 예약</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav><!-- navi 끝 -->\r\n");
      out.write("</header><!-- header 끝 -->\r\n");
      out.write("\r\n");
      out.write("<!-- section main 시작 -->\r\n");
      out.write("<section id=\"main\">\r\n");
      out.write("	<h3>좌석 선택</h3>\r\n");
      out.write("	<form name=\"floor1\" method=post\r\n");
      out.write("		action=reservation/reservation_control.jsp>\r\n");
      out.write("		<input type=hidden name=\"grade\" value=\"");
      out.print(rb.getGrade());
      out.write("\">\r\n");
      out.write("		<input type=hidden name=\"action\" value=\"seat\">\r\n");
      out.write("		\r\n");
      out.write("		<!-- 테이블 1 시작 -->\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>A</th>\r\n");
      out.write("				<th>B</th>\r\n");
      out.write("				<th>C</th>\r\n");
      out.write("				<th>이동 통로</th>\r\n");
      out.write("				<th>D</th>\r\n");
      out.write("				<th>E</th>\r\n");
      out.write("				<th>F</th>\r\n");
      out.write("				<th>이동 통로</th>\r\n");
      out.write("				<th>G</th>\r\n");
      out.write("				<th>H</th>\r\n");
      out.write("				<th>I</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA01\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB01\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC01\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD01\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE01\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG01\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG01\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH01\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI01\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA02\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB02\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC02\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD02\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE02\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG02\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG02\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH02\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI02\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA03\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB03\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC03\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD03\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE03\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG03\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG03\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH03\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI03\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA04\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB04\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC04\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD04\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE04\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG04\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG04\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH04\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI04\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA05\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB05\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC05\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD05\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE05\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG05\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG05\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH05\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI05\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA06\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB06\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC06\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD06\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE06\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG06\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG06\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH06\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI06\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA07\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB07\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC07\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD07\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE07\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG07\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG07\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH07\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI07\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA08\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB08\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC08\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD08\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE08\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG08\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG08\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH08\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI08\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA09\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB09\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC09\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD09\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE09\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG09\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG09\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH09\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI09\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA10\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB10\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC10\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD10\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE10\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG10\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG10\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH10\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI10\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA11\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB11\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC11\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD11\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE11\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG11\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG11\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH11\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI11\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA12\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB12\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC12\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD12\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE12\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG12\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG12\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH12\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI12\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA13\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB13\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC13\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD13\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE13\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG13\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG13\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH13\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI13\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA14\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB14\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC14\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD14\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE14\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG14\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG14\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH14\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI14\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA15\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB15\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC15\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD15\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE15\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG15\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG15\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH15\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI15\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA16\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB16\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC16\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD16\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE16\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG16\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG16\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH16\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI16\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA17\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB17\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC17\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD17\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE17\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG17\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG17\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH17\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI17\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA18\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB18\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC18\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD18\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE18\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG18\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG18\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH18\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI18\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA19\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB19\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC19\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD19\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE19\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG19\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG19\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH19\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI19\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA20\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB20\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC20\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD20\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE20\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG20\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG20\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH20\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI20\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA21\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB21\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC21\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD21\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE21\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG21\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG21\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH21\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI21\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA22\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB22\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC22\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD22\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE22\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG22\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG22\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH22\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI22\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA23\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB23\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC23\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD23\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE23\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG23\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG23\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH23\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI23\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA24\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB24\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC24\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD24\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE24\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG24\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG24\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH24\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI24\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AA25\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AB25\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AC25\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AD25\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AE25\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG25\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AG25\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AH25\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AI25\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table><!-- 테이블 1 끝 -->\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	<form name=\"floor2\" method=post\r\n");
      out.write("		action=reservation/reservation_control.jsp>\r\n");
      out.write("		<input type=hidden name=\"action\" value=\"seat\">\r\n");
      out.write("		\r\n");
      out.write("		<table><!-- 테이블 2 시작 -->\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>J</th>\r\n");
      out.write("				<th>K</th>\r\n");
      out.write("				<th>L</th>\r\n");
      out.write("				<th>이동 통로</th>\r\n");
      out.write("				<th>M</th>\r\n");
      out.write("				<th>N</th>\r\n");
      out.write("				<th>O</th>\r\n");
      out.write("				<th>이동 통로</th>\r\n");
      out.write("				<th>P</th>\r\n");
      out.write("				<th>Q</th>\r\n");
      out.write("				<th>R</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ01\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK01\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL01\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM01\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN01\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO01\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP01\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ01\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR01\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ02\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK02\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL02\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM02\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN02\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO02\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP02\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ02\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR02\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ03\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK03\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL03\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM03\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN03\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO03\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP03\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ03\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR03\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ04\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK04\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL04\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM04\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN04\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO04\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP04\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ04\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR04\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ05\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK05\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL05\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM05\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN05\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO05\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP05\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ05\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR05\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ06\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK06\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL06\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM06\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN06\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO06\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP06\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ06\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR06\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ07\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK07\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL07\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM07\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN07\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO07\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP07\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ07\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR07\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ08\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK08\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL08\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM08\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN08\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO08\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP08\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ08\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR08\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ09\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK09\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL09\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM09\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN09\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO09\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP09\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ09\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR09\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ10\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK10\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL10\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM10\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN10\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO10\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP10\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ10\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR10\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ11\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK11\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL11\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM11\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN11\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO11\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP11\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ11\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR11\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ12\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK12\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL12\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM12\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN12\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO12\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP12\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ12\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR12\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ13\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK13\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL13\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM13\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN13\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO13\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP13\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ13\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR13\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ14\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK14\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL14\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM14\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN14\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO14\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP14\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ14\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR14\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ15\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK15\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL15\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM15\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN15\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO15\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP15\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ15\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR15\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ16\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK16\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL16\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM16\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN16\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO16\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP16\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ16\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR16\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ17\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK17\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL17\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM17\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN17\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO17\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP17\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ17\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR17\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ18\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK18\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL18\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM18\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN18\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO18\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP18\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ18\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR18\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ19\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK19\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL19\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM19\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN19\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO19\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP19\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ19\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR19\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ20\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK20\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL20\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM20\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN20\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO20\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP20\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ20\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR20\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ21\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK21\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL21\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM21\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN21\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO21\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP21\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ21\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR21\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ22\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK22\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL22\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM22\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN22\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO22\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP22\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ22\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR22\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ23\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK23\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL23\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM23\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN23\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO23\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP23\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ23\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR23\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ24\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK24\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL24\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM24\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN24\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO24\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP24\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ24\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR24\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AJ25\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AK25\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AL25\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AM25\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AN25\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AO25\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AP25\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AQ25\"></td>\r\n");
      out.write("				<td><input name=\"seat\" type=\"submit\" value=\"AR25\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table><!-- 테이블 2 끝 -->\r\n");
      out.write("	</form>\r\n");
      out.write("</section><!-- section main 끝 -->\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
