/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-10 14:24:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.module;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import cartManagement.*;

public final class myList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("cartManagement");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      java.util.ArrayList cDatas = null;
      synchronized (session) {
        cDatas = (java.util.ArrayList) _jspx_page_context.getAttribute("cDatas", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (cDatas == null){
          cDatas = new java.util.ArrayList();
          _jspx_page_context.setAttribute("cDatas", cDatas, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/index.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/form.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/reserve.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/my.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function check(cart_no) {\r\n");
      out.write("		document.location.href=\"cart/cart_control.jsp?action=edit&cart_no=\"+cart_no;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- myList.jsp -->\r\n");
      out.write("<body>\r\n");
      out.write("<header><!-- header 시작 -->\r\n");
      out.write("	<nav id=\"navi\"><!-- navi 시작 -->\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"index.jsp?CONTENTPAGE=content.jsp\">\r\n");
      out.write("				<img src=\"img/home.png\"></a></li>\r\n");
      out.write("			<li>&#5171;</li>\r\n");
      out.write("			<li><a href=\"index.jsp?CONTENTPAGE=myFlight.jsp\">마이 페이지</a></li>\r\n");
      out.write("			<li>&#5171;</li>\r\n");
      out.write("			<li><a href=\"index.jsp?CONTENTPAGE=myList.jsp\">나의 저장</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav><!-- navi 끝 -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "left.jsp", out, false);
      out.write("\r\n");
      out.write("</header><!-- header 끝 -->\r\n");
      out.write("\r\n");
      out.write("<!-- section main 시작 -->\r\n");
      out.write("<section id=\"main\">\r\n");
      out.write("	<!-- section category 시작 -->\r\n");
      out.write("	<section id=\"category\">\r\n");
      out.write("		<h3>나의 찜 목록</h3>\r\n");
      out.write("		<input class=\"selected\" type=\"button\" value=\"관광명소\" style=\"width: 375px;\">\r\n");
      out.write("		<input type=\"button\" value=\"맛집\" style=\"width: 375px;\"><br>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"search\">\r\n");
      out.write("			<select>\r\n");
      out.write("				<option value=\"피자\">피자\r\n");
      out.write("				<option value=\"카페\">카페\r\n");
      out.write("				<option value=\"국밥\">국밥\r\n");
      out.write("			</select>\r\n");
      out.write("			<input type=\"date\" placeholder=\"연도-월-일\"> ~\r\n");
      out.write("			<input type=\"date\" placeholder=\"연도-월-일\">\r\n");
      out.write("			<input type=\"search\" placeholder=\"검색\">\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- category_list 시작 -->\r\n");
      out.write("		<div id=\"category_list\">\r\n");
      out.write("			");
 for(CartBook cb : (ArrayList<CartBook>)cDatas) { 
      out.write("\r\n");
      out.write("			<div class=\"items\" style=\"height: 200px;\">\r\n");
      out.write("				<svg class=\"list\" viewBox=\"0 0 32 32\" data-svg-content=\"true\" \r\n");
      out.write("					xmlns=\"http://www.w3.org/2000/svg\" \r\n");
      out.write("					xmlns:xlink=\"http://www.w3.org/1999/xlink\" \r\n");
      out.write("					width=\"32\" height=\"32\" fill=\"rgb(231, 76, 60)\">\r\n");
      out.write("					<g><path d=\"M 31.984,13.834C 31.9,8.926, 27.918,4.552, 23,4.552c-2.844,0-5.35,1.488-7,3.672 C 14.35,6.040, 11.844,4.552, 9,4.552c-4.918,0-8.9,4.374-8.984,9.282L0,13.834 c0,0.030, 0.006,0.058, 0.006,0.088 C 0.006,13.944,0,13.966,0,13.99c0,0.138, 0.034,0.242, 0.040,0.374C 0.48,26.872, 15.874,32, 15.874,32s 15.62-5.122, 16.082-17.616 C 31.964,14.244, 32,14.134, 32,13.99c0-0.024-0.006-0.046-0.006-0.068C 31.994,13.89, 32,13.864, 32,13.834L 31.984,13.834 z\">\r\n");
      out.write("				</path></g></svg>\r\n");
      out.write("				<a href=\"javascript:check(");
      out.print( cb.getCart_no() );
      out.write(")\">\r\n");
      out.write("				<img src=\"");
      out.print( cb.getSrc() );
      out.write("\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">");
      out.print(cb.getProduct_name() );
      out.write("</p>\r\n");
      out.write("					<p class=\"comment\">\r\n");
      out.write("						");
      out.print(cb.getProduct_detail() );
      out.write("<br> 평점\r\n");
      out.write("						");
      out.print(cb.getReview() );
      out.write('(');
      out.print(cb.getRatings() );
      out.write(") · 찜 723<br> 330km｜\r\n");
      out.write("						");
      out.print(cb.getDistinguishing() );
      out.write("<br>\r\n");
      out.write("						<br> 주소:\r\n");
      out.write("						");
      out.print(cb.getLocation() );
      out.write("<br> 전화:");
      out.print(cb.getTel() );
      out.write("<br>\r\n");
      out.write("						홈페이지: https://www.instagram.com/leejeamo…<br>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"comment\">");
      out.print(cb.getTime() );
      out.write("</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>");
 } 
      out.write("\r\n");
      out.write("		</div><!-- category_list 끝 -->\r\n");
      out.write("	</section><!-- section category 끝 -->\r\n");
      out.write("</section><!-- section main 끝 -->\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
