/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-10 14:04:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.module;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import reservationManagement.*;
import memberManagement.*;

public final class reservationProcess1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("memberManagement");
    _jspx_imports_packages.add("reservationManagement");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String selop = (String)session.getAttribute("selop");
	String str = "정렬 방법 선택"; if(selop == null) selop = "";
	if(selop.equals("pa")) str = "가격 낮은 순";
	if(selop.equals("pd")) str = "가격 높은 순";
	if(selop.equals("da")) str = "출발시간 빠른 순";
	if(selop.equals("dd")) str = "출발시간 빠른 순";

      out.write('\r');
      out.write('\n');
      java.util.ArrayList sDatas = null;
      synchronized (session) {
        sDatas = (java.util.ArrayList) _jspx_page_context.getAttribute("sDatas", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (sDatas == null){
          sDatas = new java.util.ArrayList();
          _jspx_page_context.setAttribute("sDatas", sDatas, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/form.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/reserve.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function select(schedule_no) {\r\n");
      out.write("			document.location.href = \r\n");
      out.write("				\"reservation/reservation_control.jsp?action=ssearch&schedule_no=\"+schedule_no;\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- reservationProcess1.jsp -->\r\n");
      out.write("<body>\r\n");
      out.write("<header><!-- header 시작 -->\r\n");
      out.write("	<nav id=\"navi\"><!-- navi 시작 -->\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"index.jsp?CONTENTPAGE=content.jsp\">\r\n");
      out.write("				<img src=\"img/home.png\"></a></li>\r\n");
      out.write("			<li>&#5171;</li>\r\n");
      out.write("			<li><a href=\"index.jsp?CONTENTPAGE=reservation.jsp\">항공권 예약</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav><!-- navi 끝 -->\r\n");
      out.write("</header><!-- header 끝 -->\r\n");
      out.write("\r\n");
      out.write("<!-- section main 시작 -->\r\n");
      out.write("<section id=\"main\">\r\n");
      out.write("	<form name=reservation method=post\r\n");
      out.write("		action=reservation/reservation_control.jsp>\r\n");
      out.write("		<input type=hidden name=\"action\" value=\"ssearch\">\r\n");
      out.write("		\r\n");
      out.write("		<!-- 선택 시작 -->\r\n");
      out.write("		<div id=\"selop\">\r\n");
      out.write("			<h3>항공사별 가격비교</h3>\r\n");
      out.write("			<select name=\"order\" onchange=\"location.href=this.value\">\r\n");
      out.write("				<option value=\"index.jsp?CONTENTPAGE=reservationProcess1.jsp\">");
      out.print( str );
      out.write("\r\n");
      out.write("				<option value=\"reservation/reservation_control.jsp?action=lowPrice\">가격 낮은 순\r\n");
      out.write("				<option value=\"reservation/reservation_control.jsp?action=highPrice\">가격 높은 순\r\n");
      out.write("				<option value=\"reservation/reservation_control.jsp?action=fastDeparture\">출발시간 빠른 순\r\n");
      out.write("				<option value=\"reservation/reservation_control.jsp?action=lowDeparture\">출발시간 느린 순\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>일정번호</th>\r\n");
      out.write("				<th>항공사</th>\r\n");
      out.write("				<th>출발시간</th>\r\n");
      out.write("				<th>도착시간</th>\r\n");
      out.write("				<th>출발지</th>\r\n");
      out.write("				<th>도착지</th>\r\n");
      out.write("				<th>운임료</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");
 for(ReservationBook sb : (ArrayList<ReservationBook>)sDatas) { 
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"ths\">\r\n");
      out.write("					<a href=\"javascript:select('");
      out.print( sb.getSchedule_no() );
      out.write("')\">\r\n");
      out.write("					");
      out.print( sb.getSchedule_no() );
      out.write("</a></td>\r\n");
      out.write("				<td>");
      out.print( sb.getAirplane_no() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( sb.getDeparture_time() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( sb.getArrival_time() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( sb.getStart_port() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( sb.getEnd_port() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( sb.getFreightfee() );
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("		</table><!-- 선택 끝 -->\r\n");
      out.write("	</form>\r\n");
      out.write("</section><!-- section main 끝 -->\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
