/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-20 14:15:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import smartProject.*;

public final class MemberUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/admin/Top.jsp", Long.valueOf(1637316285651L));
    _jspx_dependants.put("/admin/Bottom.jsp", Long.valueOf(1637316285570L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("smartProject");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
 
request.setCharacterEncoding("UTF-8");

      out.write('\r');
      out.write('\n');
      smartProject.MemberMgr memMgr = null;
      memMgr = (smartProject.MemberMgr) _jspx_page_context.getAttribute("memMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (memMgr == null){
        memMgr = new smartProject.MemberMgr();
        _jspx_page_context.setAttribute("memMgr", memMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>회원수정</title>\r\n");
      out.write("<link href=\"../style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script language=\"JavaScript\" src=\"script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#996600\">\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');

    String admin_id = (String)session.getAttribute("adminKey");

	if(admin_id == null) {
		response.sendRedirect("AdminLogin.jsp");
	}

      out.write("\r\n");
      out.write("<table width=\"75%\" align=\"center\" bgcolor=\"#FFFF99\">\r\n");
      out.write("  <tr bgcolor=\"#FFCC00\"> \r\n");
      out.write("    <td align=\"center\"><b><a href=\"../Index.jsp\" target=\"_blank\">사이트 홈 </a></b></td>\r\n");
      out.write("     <td align=\"center\"><b><a href=\"Index.jsp\">관리자 홈 </a></b></td>\r\n");
      out.write("    <td align=\"center\"><b><a href=\"AdminLogout.jsp\">관리자 로그아웃 </a></b></td>\r\n");
      out.write("    <td align=\"center\"><b><a href=\"MemberMgr.jsp\">회원 관리 </a></b></td>\r\n");
      out.write("    <td align=\"center\"><b><a href=\"ProductMgr.jsp\">상품 관리 </a></b></td>\r\n");
      out.write("    <td align=\"center\"><b><a href=\"OrderMgr.jsp\">주문 관리</a></b></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table> ");
      out.write('\r');
      out.write('\n');
      out.write('	');

	String mem_id = request.getParameter("mem_id");
	RegisterBean regBean= memMgr.getMember(mem_id);
	
      out.write("\r\n");
      out.write("	 \r\n");
      out.write("	<table width=\"75%\" align=\"center\" bgcolor=\"#FFFF99\">\r\n");
      out.write("	<tr> \r\n");
      out.write("	<td align=\"center\" bgcolor=\"#FFFFCC\">\r\n");
      out.write("\r\n");
      out.write("		<table width=\"95%\" align=\"center\" bgcolor=\"#FFFF99\" border=\"1\">\r\n");
      out.write("		<form name=\"regForm\" method=\"post\" action=\"MemberUpdateProc.jsp\">\r\n");
      out.write("		<tr align=\"center\" bgcolor=\"#996600\"> \r\n");
      out.write("		<td colspan=\"3\"><font color=\"#FFFFFF\"><b> \r\n");
      out.write("		");
      out.print(regBean.getMem_name());
      out.write("\r\n");
      out.write("		회원님의 정보를 수정합니다.</b></font> </td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr> \r\n");
      out.write("		<td>아이디</td>\r\n");
      out.write("		<td>");
      out.print(regBean.getMem_id());
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr> \r\n");
      out.write("		<td>패스워드</td>\r\n");
      out.write("		<td><input type=\"text\" name=\"mem_passwd\" value=\"");
      out.print(regBean.getMem_passwd());
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr> \r\n");
      out.write("		<td>이름</td>\r\n");
      out.write("		<td><input type=\"text\" name=\"mem_name\" value=\"");
      out.print(regBean.getMem_name());
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr> \r\n");
      out.write("		<td>이메일</td>\r\n");
      out.write("		<td><input type=\"text\" name=\"mem_email\"  size=\"30\" value=\"");
      out.print(regBean.getMem_email());
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr> \r\n");
      out.write("		<td>전화번호</td>\r\n");
      out.write("		<td><input type=\"text\" name=\"mem_phone\" value=\"");
      out.print(regBean.getMem_phone());
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr> \r\n");
      out.write("		<td>주소</td>\r\n");
      out.write("		<td><input type=\"text\" name=\"mem_address\" size=\"50\" value=\"");
      out.print(regBean.getMem_address());
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr> \r\n");
      out.write("		<td>직업</td>\r\n");
      out.write("		<td><select name=mem_job>\r\n");
      out.write("		<option value=\"0\">선택하세요.\r\n");
      out.write("		<option value=\"회사원\">회사원\r\n");
      out.write("		<option value=\"연구전문직\">연구전문직\r\n");
      out.write("		<option value=\"교수학생\">교수학생\r\n");
      out.write("		<option value=\"일반자영업\">일반자영업\r\n");
      out.write("		<option value=\"공무원\">공무원\r\n");
      out.write("		<option value=\"의료인\">의료인\r\n");
      out.write("		<option value=\"법조인\">법조인\r\n");
      out.write("		<option value=\"종교,언론,에술인\">종교.언론/예술인\r\n");
      out.write("		<option value=\"농,축,수산,광업인\">농/축/수산/광업인\r\n");
      out.write("		<option value=\"주부\">주부\r\n");
      out.write("		<option value=\"무직\">무직\r\n");
      out.write("		<option value=\"기타\">기타\r\n");
      out.write("		</select>\r\n");
      out.write("		<script>document.regForm.mem_job.value=\"");
      out.print(regBean.getMem_job());
      out.write("\"</script>\r\n");
      out.write("		</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr> \r\n");
      out.write("		<td colspan=\"2\" align=\"center\"><input type=\"submit\" value=\"수정완료\"> \r\n");
      out.write("		&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; \r\n");
      out.write("		<input type=\"reset\" value=\"다시쓰기\"> \r\n");
      out.write("		</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<input type=\"hidden\" name=\"mem_id\" value=\"");
      out.print(mem_id);
      out.write("\">\r\n");
      out.write("		</form>\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("	</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<table width=\"75%\" align=\"center\" bgcolor=\"#FFFF99\">\r\n");
      out.write("  <tr bgcolor=\"#FFCC00\"> \r\n");
      out.write("  <td align=\"center\">\r\n");
      out.write("  <b>Simple Shopping Mall 관리자 페이지 </b>\r\n");
      out.write("  </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table> ");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
