/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2022-01-19 14:14:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.module;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bottom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- bottom.jsp -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer 시작 -->\r\n");
      out.write("<!-- section footer_menu_box 시작 -->\r\n");
      out.write("<section id=\"footer_menu_box\">\r\n");
      out.write("	<img src=\"img/bottom.png\" alt=\"bottom\">\r\n");
      out.write("	<!-- footer_menu 시작 -->\r\n");
      out.write("	<nav id=\"footer_menu\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li class=\"footer_title\">회사소개</li>\r\n");
      out.write("			<li class=\"footer_title\">IR</li>\r\n");
      out.write("			<li class=\"footer_title\">채용정보</li>\r\n");
      out.write("			<li class=\"footer_title\">광고/제휴/출점문의</li>\r\n");
      out.write("			<li class=\"footer_title\">이용약관</li>\r\n");
      out.write("			<li class=\"footer_title\">편성기준</li>\r\n");
      out.write("			<li class=\"footer_title\">개인정보처리방침</li>\r\n");
      out.write("			<li class=\"footer_title\">법적고지</li>\r\n");
      out.write("			<li class=\"footer_title\">이메일주소무단수집거부</li>\r\n");
      out.write("			<li class=\"footer_title\">윤리경영</li>\r\n");
      out.write("			<li class=\"footer_title\">사이버감사실</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav><!-- footer_menu 끝 -->\r\n");
      out.write("\r\n");
      out.write("	<!-- section menu_box 시작 -->\r\n");
      out.write("	<section id=\"menu_box\">\r\n");
      out.write("		<div id=\"left_menu_box\">\r\n");
      out.write("			<p>(04377)서울특별시 용산구 한강대로 23길 55, 아이파크몰 6층(한강로동)</p>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>대표이사: 허민회</li>\r\n");
      out.write("				<li>사업자 등록번호: 104-81-45690</li>\r\n");
      out.write("				<li>통신판매업신고번호: 2017-서울용산-0662</li>\r\n");
      out.write("				<li><a href=\"#\">사업자정보확인</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>호스팅사업자: CJ올리브네트웍스</li>\r\n");
      out.write("				<li>개인정보보호 책임자: 심준범</li>\r\n");
      out.write("				<li>대표이메일: cjcgvmaster@cj.net</li>\r\n");
      out.write("				<li>고객센터: 1544-1122</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<p>© CJ CGV. All Rights Reserved</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	<div id=\"right_menu_box\">\r\n");
      out.write("		<p>계열사 바로가기\r\n");
      out.write("	</div>\r\n");
      out.write("</section><!-- section menu_box 끝 -->\r\n");
      out.write("</section><!-- section footer_menu_box 끝 -->\r\n");
      out.write("<!-- footer 끝 -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
