/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2022-01-19 14:13:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.module;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- content.jsp -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- section main 시작 -->\r\n");
      out.write("<section id=\"main\">\r\n");
      out.write("	<!-- section category1 시작 -->\r\n");
      out.write("	<section id=\"category1\">\r\n");
      out.write("\r\n");
      out.write("	</section><!-- section category1 끝 -->\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("	<!-- section category2 시작 -->\r\n");
      out.write("	<section id=\"category2\">\r\n");
      out.write("		<div id=\"category2_title\">\r\n");
      out.write("			<h3><a href=\"#\">무비차트</a></h3>\r\n");
      out.write("			<h3><a href=\"#\">상영예정작</a></h3>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- category2_movies 시작 -->    \r\n");
      out.write("		<div id=\"category2_movies\">       \r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie1.jpg\" alt=\"스파이더맨-노 웨이 홈\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">스파이더맨-노 웨이 홈</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">95% 예매율 27.6%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>                    \r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie2.jpg\" alt=\"특송\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">특송</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">93% 예매율 11.9%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie3.jpg\" alt=\"싱2게더\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">싱2게더</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">98% 예매율 9.6%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie4.jpg\" alt=\"해적-도깨비 깃발\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">해적-도깨비 깃발</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldeneggPreegg.png\" alt=\"eggGoldeneggPreegg\">98% 예매율 9.6%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie5.jpg\" alt=\"웨스트 사이드 스토리\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">웨스트 사이드 스토리</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegg.png\" alt=\"eggGoldenegg\">69% 예매율 7.4%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie6.jpg\" alt=\"경관의 피\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">경관의 피</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">90% 예매율 7.1%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie7.jpg\" alt=\"하우스 오브 구찌\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">하우스 오브 구찌</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">92% 예매율 6.5%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie8.jpg\" alt=\"비욘드라이브 더 무비 : 엔시티 레조넌스\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">비욘드라이브 더 무비 : 엔시티 레조넌스</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">99% 예매율 5.0%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie9.jpg\" alt=\"장민호 드라마 최종화\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">장민호 드라마 최종화</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">95% 예매율 2.3%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie10.jpg\" alt=\"킹스맨-퍼스트 에이전트\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">킹스맨-퍼스트 에이전트</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">87% 예매율 2.0%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>   \r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie11.jpg\" alt=\"어나더 라운드\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">어나더 라운드</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldeneggPreegg.png\" alt=\"eggGoldeneggPreegg\">99% 예매율 1.7%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie12.jpg\" alt=\"러브레터\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">러브레터</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldeneggPreegg.png\" alt=\"eggGoldeneggPreegg\">99% 예매율 1.5%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie13.jpg\" alt=\"클리포드 더 빅 레드 독\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">클리포드 더 빅 레드 독</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">91% 예매율 1.1%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie14.jpg\" alt=\"드라이브 마이 카\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">드라이브 마이 카</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">94% 예매율 1.0%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie15.jpg\" alt=\"킹메이커\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">킹메이커</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldeneggPreegg.png\" alt=\"eggGoldeneggPreegg\">99% 예매율 0.8%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie16.jpg\" alt=\"청춘적니\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">청춘적니</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">89% 예매율 0.7%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie17.jpg\" alt=\"프랑스\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">프랑스</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">90% 예매율 0.7%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie18.jpg\" alt=\"걸즈 앤 판처 최종장 제3화\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">걸즈 앤 판처 최종장 제3화</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">94% 예매율 0.6%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/movie19.jpg\" alt=\"극장판 소드 아트 온라인 -프로그레시브- 별 없는 밤의 아리아\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">극장판 소드 아트 온라인 -프로그레시브- 별 없는 밤의 아리아</p>\r\n");
      out.write("					<p class=\"comment\"><img src=\"img/eggGoldenegggreat.png\" alt=\"eggGoldenegggreat\">93% 예매율 0.6%</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>     \r\n");
      out.write("		</div><!-- category2_movies 끝 -->\r\n");
      out.write("	</section><!-- section category2 끝 -->\r\n");
      out.write("</section><!-- section main 끝 -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
