/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-02 06:56:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.module;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bottom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer 시작 -->\r\n");
      out.write("<section id=\"footer_menu_box\">\r\n");
      out.write("<!-- section footer_menu_box 시작 -->\r\n");
      out.write("	<nav id=\"footer_menu\">\r\n");
      out.write("	<!-- footer_menu 시작 -->\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li class=\"footer_title\">회사소개</li>\r\n");
      out.write("			<li><a href=\"#\">TRIP에 대하여</a></li>\r\n");
      out.write("			<li><a href=\"#\">기업지배구조</a></li>\r\n");
      out.write("			<li><a href=\"#\">투자정보</a></li>\r\n");
      out.write("			<li><a href=\"#\">지속가능경영</a></li>\r\n");
      out.write("			<li><a href=\"#\">뉴스룸</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li class=\"footer_title\">고객지원</li>\r\n");
      out.write("			<li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("			<li><a href=\"#\">챗봇 서비스</a></li>\r\n");
      out.write("			<li><a href=\"#\">자주 묻는 질문</a></li>\r\n");
      out.write("			<li><a href=\"#\">고객의 말씀</a></li>\r\n");
      out.write("			<li><a href=\"#\">서비스 센터</a></li>\r\n");
      out.write("			<li><a href=\"#\">e-서식함</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li class=\"footer_title\">약관 및 규정</li>\r\n");
      out.write("			<li><a href=\"#\">개인정보 처리방침</a></li>\r\n");
      out.write("			<li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("			<li><a href=\"#\">운송약관 및 고지사항</a></li>\r\n");
      out.write("			<li><a href=\"#\">소비자 안전 관련 정보</a></li>\r\n");
      out.write("			<li><a href=\"#\">운임 및 서비스 요금표</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li class=\"footer_title\">기타안내</li>\r\n");
      out.write("			<li><a href=\"#\">초등학생 견학 신청</a></li>\r\n");
      out.write("			<li><a href=\"#\">고객 안내 서비스</a></li>\r\n");
      out.write("			<li><a href=\"#\">항공교통이용자 서비스 계획</a></li>\r\n");
      out.write("			<li><a href=\"#\">항공교통이용자 피해 구제</a></li>\r\n");
      out.write("			<li><a href=\"#\">관련 사이트</a></li>\r\n");
      out.write("			<li><a href=\"#\">사이트맵</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav> <!-- footer_menu 끝 -->\r\n");
      out.write("</section> <!-- section footer_menu_box 끝 -->\r\n");
      out.write("\r\n");
      out.write("<section id=\"menu_box\">\r\n");
      out.write("<!-- section footer_box 시작 -->\r\n");
      out.write("	<div id=\"left_menu_box\">\r\n");
      out.write("		<div id=\"left_menu_box_top\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li style=\"background-color: #F3F3F3;\">대한민국</li>\r\n");
      out.write("				<li style=\"text-decoration: underline;\"><b>한국어</b></li>\r\n");
      out.write("				<li style=\"color: gray\">English</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"left_menu_box_bottom\">\r\n");
      out.write("			<p>본 콘텐츠의 저작권은 저작권자 또는 제공처에 있으며,</p>\r\n");
      out.write("			<p>이를 무단 이용하는 경우 저작권법 등에 따라 법적 책임을 질 수 있습니다.</p>\r\n");
      out.write("			<p>　</p>\r\n");
      out.write("			<p>Copyright © Trip Corp. All Rights Reserved</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"right_menu_box\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li style=\"margin-bottom: 8px;\"><b>(주)TRIP &#x1F4AC;</b></li>\r\n");
      out.write("			<li>사업자 등록번호: 000-0000-0000</li>\r\n");
      out.write("			<li>대표이사: 전채린, 엄지희</li>\r\n");
      out.write("			<li>대표전화: 1588-1598</li>\r\n");
      out.write("			<li>주소: 경기도 파주시 광탕면 분수리 47306</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</section> <!-- section footer_box 끝 -->\r\n");
      out.write("<!-- footer 끝 -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
