/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-02 06:56:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.module;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>항공권 예약 사이트 - 로그인</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/login.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String member_id  = (String)session.getAttribute("member_id");
	String member_pwd = (String)session.getAttribute("member_pwd");
	String loginSave  = (String)session.getAttribute("loginSave");
	String loginPcs = (String)session.getAttribute("loginPcs");
	String joinEnd = (String)session.getAttribute("joinEnd");
	String firstLogin = (String)session.getAttribute("firstLogin");
 	String idStr = null, pwStr = null, checkStr = null; 
 	
 	if (loginSave == null) { idStr = ""; pwStr = ""; checkStr = ""; }
 	else { idStr = member_id; pwStr = member_pwd; checkStr = "checked"; }

 	if (loginPcs == "false") {
 		
      out.write("<script>alert(\"아이디/비밀번호가 틀렸습니다!\");</script>");

		session.removeAttribute("loginPcs");
 	}
 	if (joinEnd != null) {
 		
      out.write("<script>alert(\"회원가입이 완료되었습니다!\");</script>");

		session.removeAttribute("joinEnd");
 	}
 	if (firstLogin != null) {
 		
      out.write("<script>alert(\"로그인 이후 접근 가능한 페이지입니다!\");</script>");

		session.removeAttribute("firstLogin");
 	}
 
      out.write("\r\n");
      out.write("	<header>\r\n");
      out.write("	<!-- header 시작 -->\r\n");
      out.write("		<nav id=\"navi\">\r\n");
      out.write("		<!-- navi 시작 -->\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"index.jsp?CONTENTPAGE=content.jsp\">\r\n");
      out.write("					<img src=\"img/home.png\"></a></li>\r\n");
      out.write("				<li>&#5171;</li>\r\n");
      out.write("				<li><a href=\"index.jsp?CONTENTPAGE=loginForm.jsp\">로그인</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav><!-- navi 끝 -->\r\n");
      out.write("	</header><!-- header 끝 -->\r\n");
      out.write("\r\n");
      out.write("	<section id=\"main\">\r\n");
      out.write("	<!-- section main 시작 -->\r\n");
      out.write("		<h3>로그인 - Log in Page</h3>\r\n");
      out.write("		<form id=\"login\" name=\"form2\" action=\"module/loginProcess.jsp\"\r\n");
      out.write("			method=\"get\">\r\n");
      out.write("			<fieldset id=\"login_form\">\r\n");
      out.write("				<legend class=\"hidden\">로그인</legend>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"id_area\">\r\n");
      out.write("					<div class=\"input_row\">\r\n");
      out.write("						<div class=\"img\"><img src=\"img/id.png\"></div>\r\n");
      out.write("						<div class=\"input_box\">\r\n");
      out.write("							<input id=\"id\" type=\"text\" name=\"member_id\"\r\n");
      out.write("								placeholder=\"아이디\" value=\"");
      out.print( idStr );
      out.write("\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"pw_area\">\r\n");
      out.write("					<div class=\"input_row\">\r\n");
      out.write("						<div class=\"img\"><img src=\"img/pw.png\"></div>\r\n");
      out.write("						<div class=\"input_box\">\r\n");
      out.write("							<input id=\"pw\" type=\"password\" name=\"member_pwd\"\r\n");
      out.write("								placeholder=\"비밀번호\" value=\"");
      out.print( pwStr );
      out.write("\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"etc_area\">\r\n");
      out.write("					<div id=\"linkbox\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"bdright\"><a href=\"#\">아이디 찾기</a></li>\r\n");
      out.write("							<li><a href=\"#\">비밀번호 찾기</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"checkbox\">\r\n");
      out.write("						<input type=\"checkbox\" name=\"save\" ");
      out.print( checkStr );
      out.write(">\r\n");
      out.write("						<label for=\"login_check\">아이디/비밀번호 저장</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</fieldset>\r\n");
      out.write("			\r\n");
      out.write("			<div id=\"submit_area\"><input type=\"submit\" value=\"로그인\"></div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<form action=\"index.jsp?CONTENTPAGE=joinForm.jsp\" method=\"post\">\r\n");
      out.write("			<button id=\"signup_btn\">회원가입</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</section><!-- section main 끝 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
