/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-02 06:57:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.module;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      memberManagement.ManagementBook mb = null;
      synchronized (session) {
        mb = (memberManagement.ManagementBook) _jspx_page_context.getAttribute("mb", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (mb == null){
          mb = new memberManagement.ManagementBook();
          _jspx_page_context.setAttribute("mb", mb, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function sub1(member_id) {\r\n");
      out.write("		document.location.href=\"reservation/reservation_control.jsp?action=ulist&member_id=\"+member_id;\r\n");
      out.write("	}\r\n");
      out.write("	function sub4(member_id) {\r\n");
      out.write("		document.location.href=\"management/manager_control.jsp?action=infoEdit&member_id=\"+member_id;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- myPage.jsp -->\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reservation.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("</head>\r\n");
      out.write("<header>\r\n");
      out.write("	<!-- header 시작 -->\r\n");
      out.write("		<nav id=\"navi\">\r\n");
      out.write("		<!-- navi 시작 -->\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"javascript:sub1('");
      out.print(mb.getMember_id());
      out.write("')\">나의 예약</a></li>    	\r\n");
      out.write("    			<li><a href=\"index.jsp?CONTENTPAGE=myReview.jsp\">나의 리뷰</a></li>\r\n");
      out.write("    			<li><a href=\"index.jsp?CONTENTPAGE=myList.jsp\">나의 찜목록</a></li>\r\n");
      out.write("    			<li><a href=\"javascript:sub4('");
      out.print(mb.getMember_id());
      out.write("')\">나의 정보</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav><!-- navi 끝 -->\r\n");
      out.write("	</header><!-- header 끝 -->\r\n");
      out.write("\r\n");
      out.write("<section id=\"main\">\r\n");
      out.write("<!-- section main 시작 --> \r\n");
      out.write("	<section id=\"category1\">\r\n");
      out.write("	<!-- section category1 시작 -->\r\n");
      out.write("		<h3>마이 페이지</h3>\r\n");
      out.write("        <div>\r\n");
      out.write("			<input type=\"button\" value=\"항공\" style=\"background-color: #bbb;\">\r\n");
      out.write("            <input type=\"button\" value=\"숙박\" >\r\n");
      out.write("            <input type=\"button\" value=\"투어·티켓\" style=\"background-color: #bbb;\">\r\n");
      out.write("      	</div>\r\n");
      out.write("    </section> <!-- section category1 끝 -->\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("	<section id=\"category2\">        \r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<a href=\"#\"><img src=\"img/ellisia.png\"></a>\r\n");
      out.write("				<div class=\"itemp\">\r\n");
      out.write("					<p class=\"title\">엘리시아</p>\r\n");
      out.write("					<p class=\"comment\">\r\n");
      out.write("						룸B 402호<br>\r\n");
      out.write("						2021.10.08(금) ~ 2021.10.09(토), 1박<br>\r\n");
      out.write("						자차<br>\r\n");
      out.write("						체크인 15:00 ~ 체크아웃 11:00<br>\r\n");
      out.write("						호텔 비지니스, 부산광역시 해운대구 XX로 123<br><br>\r\n");
      out.write("						대표전화: 000-0000-0000\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"price\"></p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>     \r\n");
      out.write("			</section>                                 \r\n");
      out.write("</section> <!-- section main 끝 -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
